### ISSUE TITLE
Latest version on m1

### ISSUE THREAD

**Issue by lozik4** [SergeyPirogov/webdriver_manager#451] opened 2022-10-17 12:14 UTC
from m1
not working download the latest version 

resp = <Response [404]>

    @staticmethod
    def validate_response(resp: requests.Response):
        status_code = resp.status_code
        if status_code == 404:
>           raise ValueError(f"There is no such driver by url {resp.url}")
E           ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/latest/chromedriver_mac64_m1.zip

resp       = <Response [404]>
status_code = 404

venv/lib/python3.9/site-packages/webdriver_manager/core/http.py:16: ValueError

Chrome/FireFox/Edge

**Comment by aln4739** [comment] 2022-10-17 14:06
https://github.com/SergeyPirogov/webdriver_manager/issues/446
https://github.com/SergeyPirogov/webdriver_manager/pull/445
already fixed, just no release yet

**Comment by birissou** [comment] 2022-10-18 04:31
When can we expect the next release ? This is terribly blocking !  Thanks .

**Comment by pauldambra** [comment] 2022-10-23 13:52
Version 3.8.4 includes the fix for this. 

Will close this as a duplicate of #446

**Closed by pauldambra** 2022-10-23 13:52 UTC
