### ISSUE TITLE
chromedriver unexpectedly exited: tries to download driver from */108.0.5359/chromedriver inplace of */108.0.5359.x/chromedriver LINUX

### ISSUE THREAD

**Issue by kislay-ps** [SergeyPirogov/webdriver_manager#473] opened 2022-12-20 12:44 UTC
**FULL ERROR**
` selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/108.0.5359/chromedriver unexpectedly exited. Status code was: 127`

**THE CODE**
```
import unittest
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service as ChromeService

class ConnectToLocalHostTest_Chrome(unittest.TestCase):
    def setUp(self):
        self.browser = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))
        
    def tearDown(self):
        self.browser.quit()  # quit vs close?
    
    def test_landing_page_access_chrome(self):
        browser = self.browser
        browser.get('http://localhost:8000')
        sleep(10)
        self.assertIn("Welcome", browser.title)

if __name__=='__main__':
    unittest.main()
```
I am running driver-manager in Docker with following settings and getting the same error
`OS - Linux 5.15.49-linuxkit (Docker python:3.9.16-slim base image)`
```
python==3.9.16
selenium==4.7.2
webdriver-manager==3.8.5
```

**Comment by Thomas-Boi** [comment] 2022-12-21 00:34
Consider checking your Chrome version (the executable) and make sure that it's compatible with your chrome driver.

**Comment by yusancky** [comment] 2023-01-13 06:07
@kislay-ps @infinitel8p Hi. Please try to see if #476 improves this. You can use `pip` to install it using the command below. 

```
pip install https://github.com/yusancky/webdriver_manager/archive/634bd09352732e1026cc645dd2b72a347b2680bc.zip
```

**Comment by aleksandr-kotlyar** [comment] 2023-02-05 15:20
> **FULL ERROR** ` selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/108.0.5359/chromedriver unexpectedly exited. Status code was: 127`
> 
> **THE CODE**
> 
> ```
> import unittest
> from webdriver_manager.chrome import ChromeDriverManager
> from selenium.webdriver.chrome.service import Service as ChromeService
> 
> class ConnectToLocalHostTest_Chrome(unittest.TestCase):
>     def setUp(self):
>         self.browser = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))
>         
>     def tearDown(self):
>         self.browser.quit()  # quit vs close?
>     
>     def test_landing_page_access_chrome(self):
>         browser = self.browser
>         browser.get('http://localhost:8000')
>         sleep(10)
>         self.assertIn("Welcome", browser.title)
> 
> if __name__=='__main__':
>     unittest.main()
> ```
> 
> I am running driver-manager in Docker with following settings and getting the same error `OS - Linux 5.15.49-linuxkit (Docker python:3.9.16-slim base image)`
> 
> ```
> python==3.9.16
> selenium==4.7.2
> webdriver-manager==3.8.5
> ```
summary: 
```
chromedriver unexpectedly exited: tries to download driver from */108.0.5359/chromedriver inplace of */108.0.5359.x/chromedriver LINUX
```
@kislay-ps your topic summary and error in your first message are different and not connected at all. 


> selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/108.0.5359/chromedriver unexpectedly exited. Status code was: 127

means something with your environment OS/browser/webdriver/selenium. Not the werbdriver-manager issue.
Because driver has been downloaded to `/root/.wdm/drivers/chromedriver/linux64/108.0.5359/chromedriver` - thats means webdriver-manager have done it's job.

@kislay-ps please clarify the issue and feel free to reopen or open the new one.

**Comment by aleksandr-kotlyar** [comment] 2023-02-05 15:22
@infinitel8p 

> Got the same issue, its trying to download https://chromedriver.storage.googleapis.com/108.0.5359/chromedriver_win32.zip instead of https://chromedriver.storage.googleapis.com/108.0.5359.71/chromedriver_win32.zip or https://chromedriver.storage.googleapis.com/108.0.5359.22/chromedriver_win32.zip

> Running Win 10

Your issue is different. Please open new topic and provide more info to reproduce

- OS version
- python version
- wdm version
- code to reproduce
- full log and stacktrace (with enabled webdriver-manager logger)

**Comment by aleksandr-kotlyar** [comment] 2023-02-05 15:23
Closing as invalid cause of `selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/108.0.5359/chromedriver unexpectedly exited. Status code was: 127` not a webdriver-manager issue.

**Closed by aleksandr-kotlyar** 2023-02-05 15:23 UTC
Labels: invalid
