### ISSUE TITLE
Unable to download webdriver for Brave (`no such driver version 115.56.14 for <platform>`)

### ISSUE THREAD

**Issue by ndepaola** [SergeyPirogov/webdriver_manager#613] opened 2023-09-01 01:10 UTC
I raised this is issue in #579 which was closed without an explanation. From what I can tell, no commits to master have fixed this. Maybe there was a miscommunication but this is still unresolved. Original issue below.

---

## System
* `webdriver_manager==4.0.0` (latest)
* `Brave Browser==115.0.5790.114` (latest)
* I can reliably reproduce this issue on all of the following operating systems:
    * macOS 12.6.3
    * Windows 10 22H2
    * Ubuntu 23.04

---

## Description
Howdy, I'm trying to use `webdriver_manager` to manage my Brave webdrivers (as my project supports the three major Chromium browsers), and `webdriver_manager` works correctly for Chrome and Edge but not Brave. I'm facing the following error:

`No such driver version 115.1.56.14 for <platform>`

My Brave configuration code (which matches my Chrome and Edge configuration code except for hardcoding paths to the Brave executable for each platform):

```py
def get_brave_driver(headless: bool = False, binary_location: Optional[str] = None) -> Chrome:
    options = Options()
    options.add_argument("--log-level=3")
    options.add_argument("--disable-dev-shm-usage")
    if headless:
        options.add_argument("--headless")
    options.add_experimental_option("excludeSwitches", ["enable-logging"])
    options.add_experimental_option("detach", True)

    # the binary location for brave must be manually specified
    # the below code block is partially borrowed from webdriver-manager tests:
    # https://github.com/SergeyPirogov/webdriver_manager/blob/master/tests/test_brave_driver.py
    if binary_location is not None:
        options.binary_location = binary_location
    else:
        default_binary_location = {
            OSType.LINUX: "/usr/bin/brave-browser",
            OSType.MAC: "/Applications/Brave Browser.app/Contents/MacOS/Brave Browser",
            OSType.WIN: "C:\\Program Files\\BraveSoftware\\Brave-Browser\\Application\\brave.exe",
        }[OperationSystemManager.get_os_name()]
        options.binary_location = default_binary_location

    driver = Chrome(service=Service(ChromeDriverManager(chrome_type=ChromeType.BRAVE).install()), options=options)  # type: ignore
    driver.set_network_conditions(offline=False, latency=5, throughput=5 * 125000)
    return driver
```

Let me know if you need any more detail from me. Thanks in advance!

**Comment by SergeyPirogov** [comment] 2023-09-25 06:44
Try 4.0.1

**Comment by ndepaola** [comment] 2023-09-26 12:29
I downloaded 4.0.1 on my Ubuntu machine to try it out (haven't tried on Windows or macOS yet) and I now get the following uncaught exception:

```
Traceback (most recent call last):
  ...

  File "/home/ndepaola/repos/mpc-autofill/desktop-tool/src/webdrivers/brave.py", line 33, in get_brave_driver
    driver = Chrome(service=Service(ChromeDriverManager(chrome_type=ChromeType.BRAVE).install()), options=options)  # type: ignore
  File "/home/ndepaola/repos/mpc-autofill/venv/lib/python3.9/site-packages/webdriver_manager/chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "/home/ndepaola/repos/mpc-autofill/venv/lib/python3.9/site-packages/webdriver_manager/core/manager.py", line 35, in _get_driver_binary_path
    binary_path = self._cache_manager.find_driver(driver)
  File "/home/ndepaola/repos/mpc-autofill/venv/lib/python3.9/site-packages/webdriver_manager/core/driver_cache.py", line 105, in find_driver
    driver_version = self.get_cache_key_driver_version(driver)
  File "/home/ndepaola/repos/mpc-autofill/venv/lib/python3.9/site-packages/webdriver_manager/core/driver_cache.py", line 152, in get_cache_key_driver_version
    return driver.get_driver_version_to_download()
  File "/home/ndepaola/repos/mpc-autofill/venv/lib/python3.9/site-packages/webdriver_manager/core/driver.py", line 48, in get_driver_version_to_download
    return self.get_latest_release_version()
  File "/home/ndepaola/repos/mpc-autofill/venv/lib/python3.9/site-packages/webdriver_manager/drivers/chrome.py", line 61, in get_latest_release_version
    determined_browser_version = response_dict.get("builds").get(determined_browser_version).get("version")
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by HedgeShot** [comment] 2023-09-30 12:13
getting the same error on 4.0.1 with selenium on 4.13.0 `'NoneType' object has no attribute 'get'` on a mac

**Comment by SergeyPirogov** [comment] 2023-09-30 12:18
I dont care about Brave

**Comment by SergeyPirogov** [comment] 2023-09-30 12:19
Feel free to provide a PR

**Comment by a-karro-gc** [comment] 2023-10-16 18:32
The cause is this: 
Brave reports its version as Chromium.Brave's.own.version when queried from command line.

e.g. current version is 1.59.117, based on Chromium 118.0.5993.70. As a result, Brave reports its version as 118.1.59.117, which .. kinda makes sense? but it doesn't work with the current version resolving algorithm.

**Comment by ndepaola** [comment] 2023-10-26 04:50
> I dont care about Brave

that sucks - im going to switch to selenium's built-in webdriver manager then https://www.selenium.dev/documentation/selenium_manager/

**Comment by SergeyPirogov** [comment] 2023-10-26 05:12
Good decision

**Closed by SergeyPirogov** 2023-10-26 05:12 UTC
Labels: help wanted

**Comment by GanizaniSitara** [comment] 2024-03-27 16:51
Documentation should be fixed, https://pypi.org/project/webdriver-manager/ suggests Brave works. If you don't care about it remove it from the doc?
