### ISSUE TITLE
Encountered IndexError: tuple index out of range

### ISSUE THREAD

**Issue by robertdeocampojr** [SergeyPirogov/webdriver_manager#199] opened 2021-06-03 02:45 UTC
Any idea what causing the error?

`19:12:40.255	INFO	====== WebDriver manager ======	
19:12:40.362	INFO	Current google-chrome version is 91.0.4472	
19:12:40.362	INFO	Get LATEST driver version for 91.0.4472	
19:12:41.590	INFO	There is no [win32] chromedriver for browser 91.0.4472 in cache	
19:12:41.590	INFO	Get LATEST driver version for 91.0.4472	
19:12:42.533	INFO	Trying to download new driver from https://chromedriver.storage.googleapis.com/91.0.4472.19/chromedriver_win32.zip	
19:12:52.842	INFO	[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 91.0.4472
[WDM] - Get LATEST driver version for 91.0.4472
[WDM] - There is no [win32] chromedriver for browser 91.0.4472 in cache
[WDM] - Get LATEST driver version for 91.0.4472
[WDM] - Trying to download new driver from https://chromedriver.storage.googleapis.com/91.0.4472.19/chromedriver_win32.zip	
19:12:52.844	FAIL	IndexError: tuple index out of range`

**Comment by aleksandr-kotlyar** [comment] 2021-08-03 11:32
@robertdeocampojr hello! Does it reproduce now?
If yes - can you please provide some details to reproduce the issue
- wdm version
- example of code

**Comment by aleksandr-kotlyar** [comment] 2022-02-05 14:22
Can't reproduce. Need more info.

> @robertdeocampojr please provide webdriver-manager versions and python version with example of code which fails to reproduce, and the full and verbose stacktrace.

**Comment by aleksandr-kotlyar** [comment] 2022-02-13 22:37
May be pytest-xdist is in use. If so -then #290 can be more informative issue and the current issue could be closed as a dupe.

**Comment by aleksandr-kotlyar** [comment] 2022-03-10 06:34
If you use `pytest-xdist` please watch issue #290 - it's more descriptive.
If you don't use `pytest-xdist` on version `3.5.3`+ and still get the error - feel free to reopen issue with providing more details.

Closing issue for now.

**Closed by aleksandr-kotlyar** 2022-03-10 06:34 UTC
